### ISSUE TITLE
Handle data import using datamods package

### ISSUE THREAD

**Issue by Tomeriko96** [vusaverse/vvdoctor#7]
See also #6 

On branch datamods

Current issues:

- [x] fix ui layout
- [x] remove old ui elements
- [x] statistics logic broken
- [x] default open with mtcars

**Comment by tin900** [comment]
App now uses datamods to handle importing data from various sources:
- global environment
- other packages
- external files
- google sheets
- url

While still opening the app with `mtcars` by default.
